sudo: required
services:
    - docker

before_install:
    - docker build -t fuzzythread/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fuzzythread/frontend npm run test -- --coverage